version: '3'

services:

  selenoid:
    image: "aerokube/selenoid"
    network_mode: bridge
    restart: unless-stopped
    ports:
      - "4444:4444"
    volumes:
      - "./conf/browsers.json:/etc/selenoid/browsers.json"
      - "//var/run/docker.sock:/var/run/docker.sock"
    command: ["--listen", ":4444", "--limit", "4",  "--timeout", "5m"]

  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    depends_on:
      - selenoid
    links:
      - selenoid
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

#  chrome:
#    image: selenoid/chrome:90.0
#    networks:
#      selenoid: null
#    links:
#      - selenoid
#    restart: always

#networks:
#  selenoid:
#    external: true

